name: ci
on:
  push:
    branches: ['*']
  pull_request:
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g electrode-native
      - run: yarn --frozen-lockfile
      - working-directory: android/
        run: ./gradlew createAndPublishErnDevContainer
      - working-directory: android/
        run: ./gradlew assembleDebug test lint
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g electrode-native
      - run: yarn --frozen-lockfile
      - working-directory: ios/
        run: ern create-container --out ${PWD}/container -m https://github.com/electrode-io/movies-reloaded-miniapp --platform ios
      - working-directory: ios/moviesreloadedMiniApp/
        run: xcodebuild -project "ErnRunner.xcodeproj" -scheme "ErnRunner" -destination "platform=iOS Simulator,name=iPhone 11"
